### ISSUE TITLE
TST - Library testing

### ISSUE THREAD

**Issue by emvalbuena** [KikeM/degiro-wrapper#7]
There are two things to test in this project:
1. API endpoints.
1. Valuation methods.

### API endpoints
The first one is difficult to test without having someone providing their password. Maybe we could query the endpoints without the credentials, just to see if they are still up or we need to scrap them again.

### Valuation methods
This one is easier and it has two steps in itself:
1. Processing the raw data into clean data frames.
1. Testing the valuation models. 

By generating random ISINs, prices and number of shares, one can build the `.xls` files and the data frames independently. In this way, one can make sure that
* raw data is processed correctly and
* the valuation models are not broken. 

### Tasks

* [x] `requirements-test.txt` as mentioned in #6. 
* [ ] Mock positions.
* [ ] From mock positions to `.xls` files. 
* [ ] API automatic queries without credentials.  

### Keywords

* test
* api
* valuation
